'use client'

import React from 'react'
import { Bot, ArrowLeft } from 'lucide-react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

interface VulnerabilityCardProps {
    id: string
    title: string
    description: string
    color: string
    path: string
}

export default function IngressNodePage() {
    const router = useRouter()

    // Ingress-related vulnerabilities
    const vulnerabilities = [
        {
            id: 'LLM01',
            title: 'Prompt Injection',
            description: 'Manipulating LLMs via crafted inputs can lead to unauthorized access, data breaches, and compromised decision-making.',
            color: '#3b82f6',
            path: '/labs/prompt-injection'
        },
        {
            id: 'LLM05',
            title: 'Improper Output Handling',
            description: 'Improper Output Handling refers specifically to insufficient validation, sanitization, and handling of the outputs generated by large language models before they are passed downstream to other components and systems.',
            color: '#3b82f6',
            path: '/labs/improper-output'
        },
        {
            id: 'LLM10',
            title: 'Unbounded Consumption',
            description: 'Unbounded Consumption occurs when a Large Language Model (LLM) application allows users to conduct excessive and uncontrolled inferences, leading to risks such as denial of service (DoS), economic losses, model theft, and service degradation',
            color: '#3b82f6',
            path: '/labs/unbounded-consumption'
        }
    ]

    return (
        <div className="min-h-screen bg-[#1e293b] text-white p-8">
            {/* Navigation Bar */}
            <div className="bg-gray-900/50 border-b border-gray-800 mb-8">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex items-center justify-between h-16">
                        <button
                            onClick={() => router.push('/')}
                            className="flex items-center gap-2 text-gray-300 hover:text-white transition-colors"
                        >
                            <ArrowLeft className="w-5 h-5" />
                            Back to Threat Model
                        </button>
                    </div>
                </div>
            </div>

            <div className="max-w-7xl mx-auto space-y-8">
                {/* Header */}
                <div className="space-y-4">
                    <div className="flex items-center gap-4">
                        <div className="p-4 bg-black rounded-full border-4 border-[#3b82f6]">
                            <Bot className="w-10 h-10 text-[#3b82f6]" />
                        </div>
                        <h1 className="text-4xl font-bold">Ingress Component</h1>
                    </div>
                    <p className="text-xl text-gray-300 max-w-3xl">
                        The Ingress component is the entry point for user inputs to the LLM system.
                        It handles user queries before they are processed by the LLM service.
                    </p>
                </div>

                {/* Component Description */}
                <div className="bg-gray-900/50 border border-gray-800 rounded-lg p-6">
                    <h2 className="text-2xl font-semibold mb-4">Component Overview</h2>
                    <div className="space-y-4 text-gray-300">
                        <p>
                            The Ingress component receives and pre-processes user inputs before they are sent to the
                            LLM service for processing. It serves as the first line of defense against malicious
                            inputs and is critical for ensuring system security.
                        </p>
                        <p>
                            Security vulnerabilities in the Ingress component can lead to various attacks including
                            prompt injection, unauthorized access, and service degradation through excessive
                            consumption of resources.
                        </p>
                    </div>
                </div>

                {/* Vulnerabilities Section */}
                <div>
                    <h2 className="text-2xl font-semibold mb-6">Related Vulnerabilities</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {vulnerabilities.map(vuln => (
                            <VulnerabilityCard
                                key={vuln.id}
                                id={vuln.id}
                                title={vuln.title}
                                description={vuln.description}
                                color={vuln.color}
                                path={vuln.path}
                            />
                        ))}
                    </div>
                </div>
            </div>
        </div>
    )
}

function VulnerabilityCard({ id, title, description, color, path }: VulnerabilityCardProps) {
    return (
        <Link href={path}>
            <div
                className="bg-gray-900 border border-gray-800 rounded-lg overflow-hidden hover:shadow-lg transition-all hover:scale-[1.02] cursor-pointer"
                style={{ borderLeftColor: color, borderLeftWidth: '4px' }}
            >
                <div className="p-6">
                    <div className="flex items-center gap-2 mb-3">
                        <div
                            className="text-sm font-bold px-2 py-1 rounded"
                            style={{ backgroundColor: `${color}30`, color }}
                        >
                            {id}
                        </div>
                        <h3 className="text-lg font-semibold">{title}</h3>
                    </div>
                    <p className="text-gray-300 text-sm line-clamp-3">{description}</p>
                </div>
                <div className="px-6 py-3 bg-black/20 border-t border-gray-800">
                    <div className="text-sm flex justify-between items-center">
                        <span className="text-gray-400">Go to lab</span>
                        <span style={{ color }}>→</span>
                    </div>
                </div>
            </div>
        </Link>
    )
} 