'use client'

import React from 'react'
import { Bot } from 'lucide-react'
import Link from 'next/link'
import { LabLayout } from '@/components/LabLayout'
import { LabHeader } from '@/components/LabHeader'
import { TerminalSection } from '@/components/TerminalSection'

interface VulnerabilityCardProps {
    id: string
    title: string
    description: string
    color: string
    path: string
}

const ACCENT_COLOR = '#3b82f6' // Blue for Ingress

export default function IngressNodePage() {
    // Ingress-related vulnerabilities
    const vulnerabilities = [
        {
            id: 'LLM01',
            title: 'Prompt Injection',
            description: 'Manipulating LLMs via crafted inputs can lead to unauthorized access, data breaches, and compromised decision-making.',
            color: '#3b82f6',
            path: '/labs/prompt-injection'
        },
        {
            id: 'LLM05',
            title: 'Improper Output Handling',
            description: 'Improper Output Handling refers specifically to insufficient validation, sanitization, and handling of the outputs generated by large language models before they are passed downstream to other components and systems.',
            color: '#3b82f6',
            path: '/labs/improper-output'
        },
        {
            id: 'LLM10',
            title: 'Unbounded Consumption',
            description: 'Unbounded Consumption occurs when a Large Language Model (LLM) application allows users to conduct excessive and uncontrolled inferences, leading to risks such as denial of service (DoS), economic losses, model theft, and service degradation',
            color: '#3b82f6',
            path: '/labs/unbounded-consumption'
        }
    ]

    return (
        <LabLayout>
            <div className="text-white p-8">
                <div className="max-w-7xl mx-auto space-y-8">
                    {/* Header */}
                    <LabHeader
                        labNumber="INGRESS"
                        title="Ingress Component"
                        description="The Ingress component is the entry point for user inputs to the LLM system. It handles user queries before they are processed by the LLM service."
                        icon={Bot}
                        accentColor={ACCENT_COLOR}
                    />

                    {/* Component Description */}
                    <TerminalSection title="Component Overview" accentColor={ACCENT_COLOR}>
                        <div className="space-y-4 text-[#8892a6]">
                            <p>
                                The Ingress component receives and pre-processes user inputs before they are sent to the
                                LLM service for processing. It serves as the first line of defense against malicious
                                inputs and is critical for ensuring system security.
                            </p>
                            <p>
                                Security vulnerabilities in the Ingress component can lead to various attacks including
                                prompt injection, unauthorized access, and service degradation through excessive
                                consumption of resources.
                            </p>
                        </div>
                    </TerminalSection>

                    {/* Vulnerabilities Section */}
                    <TerminalSection title="Related Vulnerabilities" accentColor={ACCENT_COLOR}>
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                            {vulnerabilities.map(vuln => (
                                <VulnerabilityCard
                                    key={vuln.id}
                                    id={vuln.id}
                                    title={vuln.title}
                                    description={vuln.description}
                                    color={vuln.color}
                                    path={vuln.path}
                                />
                            ))}
                        </div>
                    </TerminalSection>
                </div>
            </div>
        </LabLayout>
    )
}

function VulnerabilityCard({ id, title, description, color, path }: VulnerabilityCardProps) {
    return (
        <Link href={path} className="block group">
            <div
                className="bg-[#1a1f2e] border-2 rounded-lg overflow-hidden transition-all hover:scale-[1.02] cursor-pointer h-full flex flex-col"
                style={{ 
                    borderColor: `${color}33`,
                    boxShadow: `0 0 20px ${color}1a`
                }}
            >
                <div className="p-6 flex-grow">
                    <div className="flex items-center gap-2 mb-3">
                        <div
                            className="text-sm font-bold font-mono px-2 py-1 rounded"
                            style={{ backgroundColor: `${color}20`, color }}
                        >
                            {id}
                        </div>
                        <h3 className="text-lg font-semibold font-mono text-[#e8e9ed]">{title}</h3>
                    </div>
                    <p className="text-[#8892a6] text-sm line-clamp-3">{description}</p>
                </div>
                <div className="px-6 py-3 bg-[#0a0e14] border-t flex justify-between items-center" style={{ borderColor: `${color}33` }}>
                    <span className="text-sm font-mono text-[#8892a6]">Go to lab</span>
                    <span className="text-sm font-mono group-hover:translate-x-1 transition-transform inline-block" style={{ color }}>→</span>
                </div>
            </div>
        </Link>
    )
} 